package com.lumination.leadme;

import android.graphics.drawable.Drawable;

import java.util.ArrayList;

public class ConnectedPeer {

    private final String TAG = "ConnectedPeer";

    public static final int STATUS_SUCCESS = 0;
    public static final int STATUS_ERROR = 1;
    public static final int STATUS_INSTALLING = 2;
    public static final int STATUS_BLACKOUT = 3;
    public static final int STATUS_LOCK = 4;
    public static final int STATUS_UNLOCK = 5;
    public static final int STATUS_OFF_TASK = 6;
    public static final int STATUS_WARNING = 7;

    public static final int PRIORITY_TOP = 2;
    public static final int PRIORITY_HIGH = 1;
    public static final int PRIORITY_STD = 0;
    private int priority = 0;

    private String buddyName;
    private String uuid; //self-generated, for re-connections
    private String id; //generated by nearby connections library
    private boolean selected = false;
    private Drawable icon = null;

    private int status = ConnectedPeer.STATUS_SUCCESS;
    private boolean locked = true;
    private boolean blackedOut = false;

    //assume the best, update if the worst
    private boolean onTask = true;
    private boolean accessEnabled = true;
    private boolean overlayEnabled = true;
    private boolean internetEnabled = true;
    private boolean lastAppLaunchSucceeded = true;

    private NearbyPeersManager.Endpoint myEndpoint;

    //FOR TESTING ONLY//
    public ConnectedPeer(String name, String id) {
        this.buddyName = name;
        this.id = id;
    }

    //CORRECT CONSTRUCTOR
    public ConnectedPeer(NearbyPeersManager.Endpoint endpoint) {
        if (endpoint != null) {
            myEndpoint = endpoint;
            String[] name = endpoint.getName().split(":");
            buddyName = name[0];// endpoint.getName();
            if (name.length == 2) {
                uuid = name[1];
            }
            id = endpoint.getId();
        }
    }

    protected NearbyPeersManager.Endpoint getMyEndpoint() {
        return myEndpoint;
    }

    protected String getUUID() {
        return uuid;
    }

    public void setWarning(String warning, boolean success) {
        //Log.w(TAG, "Setting warning state: " + warning + ", " + success);

        switch (warning) {
            case LeadMeMain.AUTO_INSTALL_FAILED:
                hiddenAlerts.remove("launchSuccess");
                lastAppLaunchSucceeded = false; //if it failed, it's always false here
                break;
            case LeadMeMain.APP_TAG:
                hiddenAlerts.remove("launchSuccess");
                lastAppLaunchSucceeded = success;
                break;
            case LeadMeMain.STUDENT_NO_OVERLAY:
                hiddenAlerts.remove("overlayOn");
                overlayEnabled = success;
                break;
            case LeadMeMain.STUDENT_NO_ACCESSIBILITY:
                hiddenAlerts.remove("accessOn");
                accessEnabled = success;
                break;
            case LeadMeMain.STUDENT_NO_INTERNET:
                hiddenAlerts.remove("internetOn");
                internetEnabled = success;
                break;
            case LeadMeMain.STUDENT_OFF_TASK_ALERT:
                hiddenAlerts.remove("onTask");
                onTask = success;
                break;
        }
    }

    public String lastApp = "none";

    public void setLastLaunchedApp(String lastApp) {
        this.lastApp = lastApp;
    }

    public String getAlertsList() {
        String res = "";

        if (status == STATUS_ERROR) {
            res += "• DISCONNECTED FROM GUIDE\n";
        }
        if (!onTask && !hiddenAlerts.contains("onTask")) {
            res += "• Might be off task\n";
        }
        if (!lastAppLaunchSucceeded && !hiddenAlerts.contains("launchSuccess")) {
            res += "• Last app (" + lastApp + ") did not launch\n";
        }
        if (!accessEnabled && !hiddenAlerts.contains("accessOn")) {
            res += "• Accessibility service disabled\n";
        }
        if (!overlayEnabled && !hiddenAlerts.contains("overlayOn")) {
            res += "• Locking overlay disabled\n";
        }
        if (!internetEnabled && !hiddenAlerts.contains("internetOn")) {
            res += "• No internet connection\n";
        }
        if (res.isEmpty() && status == STATUS_WARNING) {
            res += "• Unspecified warning\n";
        }
        //Log.w(TAG, "Returning warning list: "+res);
        return res.trim();
    }

    public void setStatus(int newStatus) {
        //Log.d(TAG, "Setting status to " + newStatus + " in ConnectedPeer " + id);
        if (newStatus == STATUS_SUCCESS) {
            //changes nothing! Still need to display the warnings/other states
            return;
        }

        if (newStatus == STATUS_BLACKOUT) {
            blackedOut = true;
            locked = false;

        } else if (newStatus == STATUS_LOCK) {
            locked = true;
            blackedOut = false;

        } else if (newStatus == STATUS_UNLOCK) {
            locked = false;
            blackedOut = false;

        } else {
            //update warning status
            status = newStatus;
        }
    }

    //helpful for debugging
    public static String statusToString(int status) {
        switch (status) {
            case STATUS_LOCK:
                return "locked";

            case STATUS_UNLOCK:
                return "unlocked";

            case STATUS_BLACKOUT:
                return "screen blocked";

            case STATUS_ERROR:
                return "disconnected";

            case STATUS_WARNING:
                return "warning";

            case STATUS_INSTALLING:
                return "installing";

            case STATUS_SUCCESS:
                return "success";
        }

        return "unknown";
    }

    public boolean hasWarning() {
        //Log.d(TAG, "Warning? ("+getAlertsList()+") "+(!getAlertsList().isEmpty()));
        return !getAlertsList().isEmpty(); // !(onTask && accessEnabled && overlayEnabled && lastAppLaunchSucceeded && internetEnabled);
    }

    private ArrayList<String> hiddenAlerts = new ArrayList<>();

    public void hideAlerts(boolean hide) {
        if (!onTask) {
            if (hide) {
                hiddenAlerts.add("onTask");
            } else {
                hiddenAlerts.remove("onTask");
            }
        }
        if (!lastAppLaunchSucceeded) {
            if (hide) {
                hiddenAlerts.add("launchSuccess");
            } else {
                hiddenAlerts.remove("launchSuccess");
            }
        }
        if (!accessEnabled) {
            if (hide) {
                hiddenAlerts.add("accessOn");
            } else {
                hiddenAlerts.remove("accessOn");
            }
        }
        if (!overlayEnabled) {
            if (hide) {
                hiddenAlerts.add("overlayOn");
            } else {
                hiddenAlerts.remove("overlayOn");
            }
        }
        if (!internetEnabled) {
            if (hide) {
                hiddenAlerts.add("internetOn");
            } else {
                hiddenAlerts.remove("internetOn");
            }
        }
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public int getPriority() {
        return priority;
    }

    public int getStatus() {
        if (status == STATUS_WARNING && !hasWarning()) {
            //all warnings have been removed, update status
            status = STATUS_SUCCESS;
        }
        return status;
    }

    public boolean isLocked() {
        return locked;
    }

    public boolean isBlackedOut() {
        return blackedOut;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public void setIcon(Drawable drawable) {
        icon = drawable;
    }

    public Drawable getIcon() {
        return icon;
    }

    public boolean hasDisplayName() {
        return !(buddyName == null || buddyName.length() == 0);
    }

    public String getID() {
        if (id == null) {
            return "";
        }
        return id;
    }

    public String getDisplayName() {
        if (hasDisplayName()) {
            return buddyName;
        }
        return "Anonymous";
    }

}
